trigger:
- main   # runs on commits to main branch

pool:
  vmImage: 'windows-latest'

steps:
- script: echo "Installing dependencies..."
  displayName: "Install"

- script: echo "Running tests..."
  displayName: "Test"

- script: echo "Building app..."
  displayName: "Build"
