name: Build SQLCHECK
# manually triggered workflow
on:
  push:
    branches: [main]
  workflow_dispatch:
      
env:
    SOLUTION_FILE_PATH: SQLCHECK.sln
    BUILD_CONFIGURATION: Release
jobs:
    build:
      runs-on: windows-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Build It
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:RunCodeAnalysis=False /p:DeleteExistingFiles=True /bl
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: SQLCHECK.EXE
          path: "SQLCHECK\\SQLCHECK\\bin\\Debug"
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/1.5.1683.0
          asset_path: ./SQLCHECK/SQLCHECK/bin/Debug/SQLCHECK.exe
          asset_name: SQLCHECK.EXE
          asset_content_type: application/octet-stream
